/**
 * `@mx-loom/mcp` (T109 / #17) — the **generated MCP server** for the mx-loom tool
 * fabric.
 *
 * The universal binding: it turns the canonical `@mx-loom/registry` descriptor set
 * into a live Model Context Protocol endpoint every MCP-capable target runtime
 * (Claude/ADK/OpenCode/custom) can speak — the MCP half of locked design decision
 * #1 ("both bindings in parallel"). Pi is the documented exception from T204: it
 * has no built-in MCP client today, so the Pi arm uses native tool registration and
 * treats this package as reference code rather than a runtime dependency.
 *
 * Tools are generated by enumerating the registry (never hand-authored per tool);
 * the normalized T102 result envelope — including the
 * `awaiting_approval` deferred status — maps onto an MCP `CallToolResult`; the same
 * server runs over stdio or Streamable HTTP.
 *
 * Secret-free by construction: every daemon call routes through the toolbelt
 * `MxClient`/`MxSession`, so the deny-by-default env allowlist, outbound
 * credential-shaped-arg rejection, and inbound `redactSecrets` all stay in force,
 * and every enforcement decision (trust / policy / approval) stays out-of-process
 * on the receiving mx-agent daemon. This package surfaces only the nine
 * model-facing verbs; no trust/policy/approval mutation tool is reachable.
 *
 * Library surface (for T110 / T201 / T203 / T114 to embed or drive the server
 * programmatically; T205/Pi uses it only as a pattern) + the `mx-loom-mcp` `bin`
 * (see `cli.ts`).
 */

// The server assembly — low-level `Server` + the list/call handlers + the single
// `withAudit` chokepoint.
export { createMcpServer, SERVER_NAME, SERVER_VERSION } from './server.js';
export type { CreateMcpServerOptions } from './server.js';

// The binding context — the secret-free daemon/room/audit bundle + its factory
// (opens an `MxSession`, or binds an injected session / bare `DaemonCall`).
export { createBindingContext } from './context.js';
export type { BindingContext, CreateBindingContextOptions } from './context.js';

// The tool generator — `CANONICAL_TOOLS` → MCP `Tool[]` (verbatim JSON Schema).
export { buildToolList, ASYNC_SEMANTICS_META_KEY } from './tools.js';

// The envelope serializer — `ToolResult` → MCP `CallToolResult` (the AC2/AC3 crux).
export { serializeToolResult } from './serialize.js';

// The dispatch table + router — name → registry handler.
export { DISPATCH, dispatchCall } from './dispatch.js';
export type { DispatchEntry, ToolArgs } from './dispatch.js';
